### PR TITLE
New settings page

### PR DESCRIPTION
**Pull request by Jaqueeee**
Added password prompt on seed view
added option to change daemon/adress with automatic reconnection to daemon

### CODE REVIEW

**Comment by mbg033** [comment]
please rebase

**Comment by Jaqueeee** [comment]
rebased.

**Comment by mbg033** [comment]
@Jaqueeee it seems my bad, sorry, master wasn't synchronized with monero-project's master. Please rebase one more time, PR should contain only your commits

**Comment by Jaqueeee** [comment]
no worries. Just realized I PR'd against the master branch. Changed to develop to avoid conflicts.

**Pull request merged**
